import * as mongoose from 'mongoose';

export const OrderSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      minLength: [3, 'first name must be at least 3 characters long'],
    },
    totalOrderPrice: Number,
    evt_id: String,
    description: {},
    address: String,
    user_id: String,
    currency: String,
    email: String,
    payment_method_types: String,
    payment_intent: String,
    status: String,
    typeSystem: String,
    ExpiryDate: String,
    PhoneNumber: String,
    adultsDataState: String,
    GenderBooking: String,
    BirthDateBooking: String,
    NationalityBooking: String,
    CountryBooking: String,
    PassportNumberBooking: String,
    typeTravelState: String,
    tripData: {},
    metaData: {
      description: String,
      logo: String,
      price: String,
      timeGo: String,
      timeSet: String,
      user_id: String,
      durationH: String,
      durationM: String,
      isStope: Number,
    },
  },
  {
    timestamps: true,
  },
);
